### ISSUE TITLE
Robotiq gripper joints do not move as expected in Rviz

### ISSUE THREAD

**Issue by planetceres** [AcutronicRobotics/MARA_ROS1#7] opened 2019-02-13 03:37 UTC
Using `test_mara_model.launch` to launch RViz and the joint state publisher, the joints of the gripper do not move in a coordinated manner as shown in the screenshots below.

![mara_00](https://user-images.githubusercontent.com/7258207/52685072-3f976200-2efd-11e9-8eb9-7bc015b3ce69.png)
![mara_01](https://user-images.githubusercontent.com/7258207/52685074-42925280-2efd-11e9-9318-6092242e680c.png)
![mara_03](https://user-images.githubusercontent.com/7258207/52685075-445c1600-2efd-11e9-8787-d6bcb2165424.png)

How can the Robotiq gripper be properly used in simulation so that all joints move together and do not become detached from one another?

**Comment by vmayoral** [comment] 2019-02-13 04:17
Thanks for reporting @planetceres, let us have a look and get back to you.

**Comment by vmayoral** [comment] 2019-02-13 04:18
@ahcorde, maybe worth reviewing if this also applies to https://github.com/AcutronicRobotics/MARA in ROS 2?

**Comment by ahcorde** [comment] 2019-02-13 09:15
This gripper has a parallel mechanism. URDFs are not friends of this kind of circular link connections. Each finger is a circular link. 

I have to use a trick, the URDF only contain 3 joints, but in Gazebo cointains the 4 joints. Because I use the tag [gazebo](https://github.com/AcutronicRobotics/MARA_ROS1/blob/master/robotiq_140_gripper_description/urdf/robotiq_140.urdf.xacro#L349-L386).

In ROS 2.0 for sure is happening the same thing. because URDF are pretty similar. the main differences are the plugins that the robot make use (ROS or ROS 2.0)

It's a problem of the URDF library. Not allowing to create circular link connections.

Maybe I can fix this using the tag `mimic`

**Comment by ahcorde** [comment] 2019-02-13 10:24
I have updated the URDFs. Now it's working. I will updated the rest of the things right away.

![finger_joint](https://user-images.githubusercontent.com/1933907/52704842-cb52d200-2f81-11e9-8913-3d4b8634bbb5.gif)

**Comment by vmayoral** [comment] 2019-02-13 10:41
Thanks @ahcorde, please close it when you're done.

**Comment by ahcorde** [comment] 2019-02-13 15:08
# ROS 1

![hande](https://user-images.githubusercontent.com/1933907/52720661-51820f00-2fa8-11e9-8bfb-b6a170e9860f.gif)
![robotiq85](https://user-images.githubusercontent.com/1933907/52720662-521aa580-2fa8-11e9-9f3c-48219ab99d0f.gif)

# ROS 2.0 and rviz2 

![rviz2_ros2_service](https://user-images.githubusercontent.com/1933907/52721258-935f8500-2fa9-11e9-93b5-84354d684dad.gif)

**Closed by ahcorde** 2019-02-13 15:08 UTC
Labels: bug

**Comment by planetceres** [comment] 2019-02-13 17:31
Thanks for correcting this so quickly. However, after the update, the xacro XML will not load properly:

```
XML parsing error: mismatched tag: line 380, column 4
when processing file: /workspace/install_isolated/share/robotiq_140_gripper_description/urdf/robotiq_140.urdf.xacro
included from: /workspace/install_isolated/share/mara_description/urdf/mara_robot_gripper_140.urdf.xacro

Check that:
 - Your XML is well-formed
 - You have the xacro xmlns declaration: xmlns:xacro="http://www.ros.org/wiki/xacro"
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/kinetic/lib/xacro/xacro --inorder /workspace/install_isolated/share/mara_description/urdf/mara_robot_gripper_140.urdf.xacro] returned with code [2]. 

```

The issue persists on both ROS Melodic and Kinetic.

**Comment by ahcorde** [comment] 2019-02-13 17:35
which command are you launching in the terminal?

I will try to reproduce it

**Comment by planetceres** [comment] 2019-02-13 17:45
`roslaunch mara_description test_mara_model.launch`

**Comment by ahcorde** [comment] 2019-02-13 18:02
Solved:

you can also try with different grippers:

```bash
roslaunch mara_description test_mara_model.launch gripper:=140
roslaunch mara_description test_mara_model.launch gripper:=85
roslaunch mara_description test_mara_model.launch gripper:=hande
```
